---
booktitle: 'Proceedings of the 1st International Workshop on Feature Extraction: Modern
  Questions and Challenges at NIPS 2015'
start: 2015-12-11
end: 2015-12-11
published: 2015-12-08
volume: 44
year: '2015'
shortname: FE
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: FE-2015
month: 0
cycles: false
editor:
- given: Dmitry
  family: Storcheus
- given: Afshin
  family: Rostamizadeh
- given: Sanjiv
  family: Kumar
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the 1st International Workshop on Feature Extraction: Modern Questions and Challenges at NIPS 2015
    Held in Montreal, Canada on 11 December 2015

  Published as Volume 44 by the Proceedings of Machine Learning Research on 08 December 2015.

  Volume Edited by:
    Dmitry Storcheus
    Afshin Rostamizadeh
    Sanjiv Kumar

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 11 Dec
url: http://proceedings.mlr.press
baseurl: "/v44"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v44
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: 'Feature Extraction: Modern Questions and Challenges'
  url: 
  location: Montreal, Canada
  dates:
  - 2015-12-11
  number: 1
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
